
image: docker:stable
services:
  - docker:dind

stages:
  - test
  - build
  - release
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest


syntax-5:
  stage: test
  image: php:5
  tags:
    - docker
  script:
    - find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

syntax-7:
  stage: test
  image: php:7
  tags:
    - docker
  script:
    - find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

build_container:
  stage: build
  tags:
    - docker
    - privileged
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

# test1:
#   stage: test
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests
#
# test2:
#   stage: test
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test

release-image:
  tags:
    - docker
    - privileged
  stage: release
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

# deploy:
#   tags:
#     - docker
#     - privileged
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - master
